#include "Std_Types.h"
#include "Port.h"
#include "GPIO_Cfg.h"

Port_ConfigType Channels[DIO_CONFIGURED_CHANNLES] = {
							 {NORMAL_MODE,LOW,R4R,OPEN_DRAIN,DIRECTION_OUTPUT,{DioConf_LED1_PORT,DioConf_LED1_CHANNEL}},
							 {NORMAL_MODE,LOW,R4R,OPEN_DRAIN,DIRECTION_OUTPUT,{DioConf_LED2_PORT,DioConf_LED2_CHANNEL}},
							 {NORMAL_MODE,LOW,R4R,OPEN_DRAIN,DIRECTION_OUTPUT,{DioConf_LED3_PORT,DioConf_LED3_CHANNEL}},
							 {NORMAL_MODE,LOW,R4R,OPEN_DRAIN,DIRECTION_INPUT,{DioConf_SW1_PORT,DioConf_SW1_CHANNEL}},
							 {NORMAL_MODE,LOW,R4R,OPEN_DRAIN,DIRECTION_INPUT,{DioConf_SW2_PORT,DioConf_SW2_CHANNEL}},
};